title: L2 / Statistiques et cartographie
description: Support de cours - Statistiques et cartographie (Licence 2)
author: Kadjo Raphael

remote_theme: carlosperate/jekyll-theme-rtd
plugins:
  - jekyll-remote-theme

# Réglages du thème
edit_on_github: true
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
